version: 0.0.{build}
os: Visual Studio 2017
build:
  project: MitchEngine.sln
  parallel: true
  verbosity: normal
branches:
  only:
    - master
before_build:
  - git submodule init
  - git submodule update
  - ./GenerateSolution.bat